// Code generated by hertz generator.

package api

import (
	"context"

	api "apigateway2/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Add .
// @router calculator/add [GET]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AdditionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	req.GetNum1()
	req.GetNum2()

	resp := new(api.AdditionResponse)
	resp.Result = req.Num1 + req.Num2

	c.JSON(consts.StatusOK, resp)
}
